### ISSUE TITLE
shopify-app-remix - installGlobalResponseHeaders

### ISSUE THREAD

**Issue by bkspace** [Shopify/shopify-app-js#339] opened 2023-07-12 09:50 UTC
# Issue summary

Using the shopify-app-remix `release candidate` package from a Cloudflare environment (workers, pages, miniflare) fails on calling installGlobalResponseHeaders: `https://github.com/Shopify/shopify-app-js/blob/release-candidate/packages/shopify-app-remix/src/auth/helpers/add-response-headers.ts#L30`.

- Package: `@shopify/shopify-app-remix-rc-1`
- Node version: 18.3.0
- Operating system: macOS Ventura 13.3

```
service core:user:worker: Uncaught TypeError: Illegal invocation
  at 332dbn7d4gh.js:21340:111 in installGlobalResponseHeaders
  at 332dbn7d4gh.js:23770:26 in shopifyApp2
```

The problem is specifically caused by this line of code:

`Object.getOwnPropertyDescriptor(Response.prototype, 'headers')!;`

## Expected behavior

I am able to use `shopify-app-remix` in a Cloudflare environment.

## Actual behavior

I am not able to use `shopify-app-remix` in a Cloudflare environment.

## Steps to reproduce the problem

1. Setup a new Cloudflare worker: `wrangler init test-project`, with fetch handler
2. Add the following: `Object.getOwnPropertyDescriptor(Response.prototype, 'headers');`
3. Run the worker, and hit the endpoint, the output will be:

```
TypeError: Illegal invocation

Object.getOwnPropertyDescriptor(Response.prototype, "headers")
```

**Comment by byrichardpowell** [comment] 2023-07-26 12:27
Closing this issue since the problem is fixed in version `1.0.1` on.

**Closed by byrichardpowell** 2023-07-26 12:27 UTC
