### ISSUE TITLE
Scope mismatch warnings / error handling

### ISSUE THREAD

**Issue by TheRealFlyingCoder** [Shopify/shopify-app-js#421] opened 2023-08-25 04:04 UTC
I'm not sure if this is a global thing, or specific to the shopify-remix app, but there are multiple ways your scopes can get out of sync if you make a change because you have multiple steps:

1. Update `shopify.app.toml`
2. Push the .toml config via the CLI
3. Update your environment variables so that the `shopifyApp()` can consume them at runtime.

If you have a mismatch in your scopes (which I just did) authentication will throw in an endless loop.

There should be a warning SOMEWHERE, that says anything along the lines of `Received unexpected scopes, please confirm your configuration`.

**Comment by byrichardpowell** [comment] 2023-08-31 18:43
Hey @TheRealFlyingCoder 

Thanks for opening an issue, and sorry this has caused some pain.  

I'm going to make this as a duplicate of https://github.com/Shopify/shopify-app-template-remix/issues/286, since that issue has a lot of detail in it

We are working with the team to improve the DX here.

**Closed by byrichardpowell** 2023-08-31 18:43 UTC
