### ISSUE TITLE
`shop/update` webhook not fired for `marketing_sms_consent_enabled_at_checkout`

### ISSUE THREAD

**Issue by nullndr** [Shopify/shopify-app-js#878] opened 2024-05-14 13:27 UTC
This is not the right place to open this kind of issue but the [previous one](https://github.com/Shopify/shopify-api-js/issues/1339) was archived before I could comment further. 

I also opened a [discussion](https://community.shopify.com/c/shopify-apps/shop-update-webhook-is-not-triggered-when-i-change-the-marketing/m-p/2505148) on Shopify Community over a month ago, but the bug still persist.

So let's recap:

I have registered the `shop/update` webhook with the [`shopifyApp()`](https://github.com/Shopify/shopify-app-js/blob/43135254c14871b44ec9cf41a043bdb710a0fdd9/packages/apps/shopify-app-remix/src/server/shopify-app.ts#L60) utility in Remix successfully, if I update the email I correctly get a `shop/update` webhook with the new email.

This does not happen with the `marketing_sms_consent_enabled_at_checkout` field, updating it on the admin does not trigger any `shop/update`, even if the [changelogs](https://shopify.dev/changelog/new-field-marketing_sms_consent_enabled_at_checkout-added-to-shop-object) clearly state that it should.

Please note that if I fetch the `marketing_sms_consent_enabled_at_checkout` via REST or GraphQL I can correctly see the new value.

I use the webhook version `2024-04`

**Comment by lizkenyon** [comment] 2024-05-14 14:48
Hey there 👋 

I understand this is frustrating. I previously flagged your issue to the owning product team. They created an issue to review this functionality. I pinged them again that this is still relevant.

I will be closing this issue, as this is not a bug in the library.

**Closed by lizkenyon** 2024-05-14 14:48 UTC

**Comment by nullndr** [comment] 2024-06-05 08:25
@lizkenyon sorry to bother you, but do you have any news?
