### ISSUE TITLE
`@shopify/api-codegen-preset`: Can't download `storefront-schema.json`

### ISSUE THREAD

**Issue by Tandashi** [Shopify/shopify-app-js#1130] opened 2024-07-01 14:39 UTC
# Issue summary

Before opening this issue, I have:

- [x] Upgraded to the latest version of the relevant packages
  - `@shopify/*` package and version: `@shopify/api-codegen-preset@1.0.1`
  - Node version: 21.7.2
  - Operating system: MacOS 14.1 (Apple M3 Pro)
- [x] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration, when applicable
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

---

Currently our CI Pipelines are not able to install the dependencies and generate the respective typescript types for the Storefront API. Also on fresh local environments it is not possible to do the same. It always errors with a `Not Found`.
Maybe the API paths for the schemas has changed?

## Expected behavior

It should have downloaded the respective `storefront-schema.json` and generated the typescript types.

## Actual behavior

It doesn't download the `storefront-schema.json` like it did 3 days ago.

## Steps to reproduce the problem

1. `pnpm init`
2. `pnpm add -D @graphql-codegen/cli @shopify/api-codegen-preset`
3. `pnpm graphql-codegen`

```typescript
// .graphqlrc.ts

import { ApiType, shopifyApiProject } from '@shopify/api-codegen-preset';

export default {
  schema: 'https://shopify.dev/storefront-graphql-direct-proxy',
  documents: ['./src/**/*.{ts,tsx}', '!node_modules'],
  projects: {
    default: shopifyApiProject({
      apiType: ApiType.Storefront,
      apiVersion: '2024-04',
      outputDir: './src/client/shopify/gen',
    }),
  },
};
```

## Debug logs

```
> pnpm -v             
9.0.6

> pnpm graphql-codegen -v -d
(node:34669) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[STARTED] Parse Configuration
[SUCCESS] Parse Configuration
[STARTED] Generate outputs
[STARTED] Generate to ./src/client/shopify/gen/storefront-2024-04.schema.json
[STARTED] Generate to ./src/client/shopify/gen/storefront.types.d.ts
[STARTED] Generate to ./src/client/shopify/gen/storefront.generated.d.ts
[STARTED] Load GraphQL schemas
[STARTED] Load GraphQL schemas
[STARTED] Load GraphQL schemas
[FAILED] Not Found
[FAILED] Not Found
[FAILED] Not Found
[SUCCESS] Generate outputs
Running lifecycle hook "afterStart" scripts...
[CLI] Loading Schemas
[CLI] Loading Schemas
[CLI] Loading Schemas
```

**Comment by fabiofcferreira** [comment] 2024-07-01 17:00
Related to https://github.com/Shopify/shopify-app-js/issues/1128

**Comment by matteodepalo** [comment] 2024-07-02 10:40
Hi @Tandashi, I'm going to close this a duplicate of https://github.com/Shopify/shopify-app-js/issues/1128 so please follow the progress of the issue there.

**Closed by matteodepalo** 2024-07-02 10:40 UTC
