### ISSUE TITLE
Script Tags not working inside the Shopify app page iframe

### ISSUE THREAD

**Issue by mason2205** [Shopify/shopify-app-js#483] opened 2023-10-28 04:26 UTC
# Issue summary

- `@shopify/shopify-app-remix` package and version:
- Node version: v18.16.0
- Operating system: MacOS, Linux

```
// Paste any relevant logs here
```

## Expected behavior

Should allow Content Secure Policy for external chat widget script, ex: tawk.to
## Actual behavior

The remix app loading in a iframe and they prevent the loading of external chat widget, so I can't load my chat widget
## Steps to reproduce the problem

1. Following the tawk integration guide: https://help.tawk.to/article/react-js, I added that library & using it in root of my remix component
2. Open my admin shopify app, then I don't found the chat bubble loading at the right bottom of site
3. I know that the remix app doesn't allow CSP for the external chat widget. So I guess that's an issue
![Screenshot 2023-10-28 at 10 51 42](https://github.com/Shopify/shopify-app-js/assets/142089536/c47047c5-54df-4538-996b-231f942e29b1)

I hope the team will give me the solution to fix it.
Thanks & best regard!

**Comment by lizkenyon** [comment] 2023-11-01 15:49
Hi there 👋 

I am going to close this issue as its is a duplicate of [this issue](https://github.com/Shopify/shopify-app-template-remix/issues/364). Please follow along there for updates.

**Closed by lizkenyon** 2023-11-01 15:49 UTC
