### ISSUE TITLE
Delete application recurring charge is not working for the node lib

### ISSUE THREAD

**Issue by yovasx2** [Shopify/shopify-app-js#760] opened 2024-03-07 21:42 UTC
# Issue summary
Delete application recurring charge is not working for the node lib

Before opening this issue, I have:

- [x] Upgraded to the latest version of the package
  - `@shopify/shopify-api` version: @shopify/shopify-api@9.3.0
  - Node version: 18.4
  - Operating system: MacOS Sonoma 14.3.1 (23D60)
- [x] Set `{ logger: { level: LogSeverity.Debug } }` when calling [`shopifyApi()`](https://github.com/Shopify/shopify-api-js/blob/main/packages/shopify-api/docs/reference/shopifyApi.md#logger), if applicable
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

Getting:
```
Error cancelling plan: FetchError: invalid json response body at 
https://idpartner-test.myshopify.com/admin/api/2024-01/recurring_application_charges/32169951552.json reason: Unexpected end of JSON 
input
15:27:35 │ web-backend  │     at /Users/yovasx2/shopify/idpartner/web/node_modules/node-fetch/lib/index.js:273:32
15:27:35 │ web-backend  │     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
15:27:35 │ web-backend  │   type: 'invalid-json'
15:27:35 │ web-backend  │ }
```
While using the https://shopify.dev/docs/api/admin-rest/2024-01/resources/recurringapplicationcharge#delete-recurring-application-charges-recurring-application-charge-id endpoint
like showed in the node example:
```
// Session is built by the OAuth process

await shopify.rest.RecurringApplicationCharge.delete({
  session: session,
  id: 455696195,
});
```

It's used via shopify-app-express with version 4.1

## Expected behavior
HAve no error
What do you think should happen?
cancel and return
## Actual behavior
gets a parsing error due to empty json returned

What actually happens?
returns an error
## Steps to reproduce the problem

1. create subs
1. tried to delete it

## Debug logs

```
// Paste any relevant logs here
```

**Comment by paulomarg** [comment] 2024-04-17 17:22
Hey folks, thanks for your patience. We re-evaluated this issue, and it seems that it happens enough that we should handle this scenario in the library. We'll look into it while the issue isn't addressed in the API itself.

**Closed as completed** 2024-05-01 19:47 UTC
